name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: make docker_image
    - name: Upload the Docker image
      env:
        DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      run: |
        docker login -u fredrikfornwall -p $DOCKER_HUB_ACCESS_TOKEN
        make push_docker_image
    - name: Deploy to Fly
      uses: superfly/flyctl-actions@master
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        FLY_PROJECT_PATH: flask_web
      with:
        args: "deploy"
